AWSTemplateFormatVersion: '2010-09-09'
Description: 'ANF Infrastructure Stack - Main Template'

Parameters:
  EnvironmentName:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - prod
    Description: 'Deployment environment (dev or prod)'

  DomainName:
    Type: String
    Description: 'ドメイン名（例:example.com）'

  HostedZoneId:
    Type: String
    Description: 'Route53の該当ドメインのホストゾーンID（要事前設定）'
  
  DBUsername:
    Type: String
    Description: 'DB Username'
    NoEcho: true

  DBPassword:
    Type: String
    Description: 'DB Password'
    NoEcho: true

Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://anf-cloudfomation.s3.ap-northeast-1.amazonaws.com/templates/vpc.yml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  SecurityGroupsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://anf-cloudfomation.s3.ap-northeast-1.amazonaws.com/templates/security-groups.yml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  EC2Stack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://anf-cloudfomation.s3.ap-northeast-1.amazonaws.com/templates/ec2.yml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        WebSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.WebSecurityGroupId

  ACMStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://anf-cloudfomation.s3.ap-northeast-1.amazonaws.com/templates/acm.yml'
      Parameters:
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId

  ALBStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://anf-cloudfomation.s3.ap-northeast-1.amazonaws.com/templates/alb.yml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        ElbSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.ElbSecurityGroupId
        WebSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.WebSecurityGroupId
        EC2InstanceId: !GetAtt EC2Stack.Outputs.EC2InstanceId
        SSLCertificateArn: !GetAtt ACMStack.Outputs.SSLCertificateArn

  Route53Stack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://anf-cloudfomation.s3.ap-northeast-1.amazonaws.com/templates/route53.yml'
      Parameters:
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        LoadBalancerDNSName: !GetAtt ALBStack.Outputs.LoadBalancerDNSName
        AlbCanonicalHostedZoneID: !GetAtt ALBStack.Outputs.AlbCanonicalHostedZoneID

  RDSStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://anf-cloudfomation.s3.ap-northeast-1.amazonaws.com/templates/rds.yml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        DbSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.DbSecurityGroupId
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
