AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS Aurora Template'

Parameters:
  EnvironmentName:
    Type: String
    Description: 'Deployment environment (dev or prod)'
  
  VpcId:
    Type: String
    Description: 'VPC ID'

  PrivateSubnetIds:
    Type: CommaDelimitedList
    Description: 'Private Subnet IDs'

  DbSecurityGroupId:
    Type: String
    Description: 'DB Security Group ID'

  DBUsername:
    Type: String
    Description: 'DB Username'
    NoEcho: true

  DBPassword:
    Type: String
    Description: 'DB Password'
    NoEcho: true

Resources:
  AnfAuroraCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      Engine: 'aurora-mysql'
      EngineVersion: '8.0.mysql_aurora.3.04.1'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref AnfDBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DbSecurityGroupId
      StorageEncrypted: true
      DeletionProtection: true
      ServerlessV2ScalingConfiguration: 
        MaxCapacity: 1.5
        MinCapacity: 0.5
      Tags:
        - Key: 'Name'
          Value: !Sub 'anf-${EnvironmentName}-aurora-cluster'

  AnfDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'Subnet group for ANF Aurora Cluster'
      SubnetIds: !Ref PrivateSubnetIds
      Tags:
        - Key: 'Name'
          Value: !Sub 'anf-${EnvironmentName}-db-subnet-group'
  
  AnfAuroraInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: 'aurora-mysql'
      DBClusterIdentifier: !Ref AnfAuroraCluster
      DBInstanceClass: db.serverless
      PubliclyAccessible: false
      Tags:
        - Key: 'Name'
          Value: !Sub 'anf-${EnvironmentName}-aurora-instance'


Outputs:
  AuroraClusterEndpoint:
    Description: 'Aurora Cluster Endpoint'
    Value: !GetAtt AnfAuroraCluster.Endpoint.Address

